name: Sync Gmail to Caspio

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Google credentials from secrets
        run: |
          echo "${{ secrets.GMAIL_CREDENTIALS_JSON }}" > credentials.json
          echo "${{ secrets.GMAIL_TOKEN_JSON }}" > token.json
      
      # --- ADD THIS NEW STEP FOR DEBUGGING ---
      - name: Debug file contents
        run: |
          echo "--- Content of credentials.json ---"
          cat credentials.json
          echo "--- End of credentials.json ---"
          echo "--- Content of token.json ---"
          cat token.json
          echo "--- End of token.json ---"
        
      - name: Run the sync script
        env:
          CASPIO_CLIENT_ID: ${{ secrets.CASPIO_CLIENT_ID }}
          CASPIO_CLIENT_SECRET: ${{ secrets.CASPIO_CLIENT_SECRET }}
        run: python main_script.py
