# name: Sync Gmail to Caspio

# on:
#   schedule:
#     - cron: '*/10 * * * *'
#   workflow_dispatch:

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
        
#       - name: Run the sync script
#         env:
#           CASPIO_CLIENT_ID: ${{ secrets.CASPIO_CLIENT_ID }}
#           CASPIO_CLIENT_SECRET: ${{ secrets.CASPIO_CLIENT_SECRET }}
#           GMAIL_CREDENTIALS_JSON: ${{ secrets.GMAIL_CREDENTIALS_JSON }}
#           GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
#         run: python main_script.py
